### ISSUE TITLE
userResDecorator never gets called (Resolved - Status 304)

### ISSUE THREAD

**Issue by jsammarco** [villadora/express-http-proxy#290] opened 2017-10-13 16:41 UTC
The userResDecorator never gets called. I want to trim the response to clean up bad XML with a couple leading spaces. Maybe I'm doing something wrong? Here is my options object.
Thanks

```
proxyConfig = {
      timeout: 5000,
      parseReqBody: true,
      preserveHostHdr: true,
      userResDecorator: function(proxyRes, proxyResData, userReq, userRes) {
        data = JSON.parse(proxyResData.toString('utf8'));
        data.newProperty = 'exciting data';
        console.log(123);
        return JSON.stringify(data);
      },
      proxyReqPathResolver: function(req,test) {
        return require('url').parse(req.url).path;
      }
    }
```

**Comment by jsammarco** [comment] 2017-10-13 18:43
So I believe this is not an issue, I must have been getting a 304 because I added ?adsfasdfgasg to my request and got a 200 and now I see my console.log come through and I'm able to filter.
Thanks,
Joe

**My Code**
```
proxyConfig = {
      timeout: 5000,
      parseReqBody: true,
      preserveHostHdr: true,
      userResDecorator: function(proxyRes, proxyResData, userReq, userRes) {
        data = proxyResData.toString('utf8').trim();
        console.log(userReq.url, data);
        return data;
      },
      proxyReqPathResolver: function(req,test) {
        return require('url').parse(req.url).path;
      }
    };
```

**Comment by m7mdbadawy** [comment] 2017-10-31 17:45
Is this the intended behavior? I had the same issue with `userResHeaderDecorator` and I used `skipToNextHandlerFilter` to change a header before sending response back

**Comment by monkpow** [comment] 2017-11-13 17:15
It is the intended behavior.    

```
 if (res.statusCode === 304) {
    debug('Skipping userResDecorator on response 304');
    return Promise.resolve(container);
  }
```

Since 304 does not send a representation of the data back with it; instead signaling the client to use the prior response.      There are a couple of outstanding requests to break up decorateRes from decorateHeader, and so that might make @m7mdbadawy's case easier to handle, but is not part of the library today.

Open to more discussion on this, but hope this description of the working today helps.

**Comment by monkpow** [comment] 2017-11-13 17:18
I've added #298 (https://github.com/villadora/express-http-proxy/issues/298) to capture this concern.   I'm going to close this thread, but feel free to reopen if you'd like to continue the conversation.

**Closed by monkpow** 2017-11-13 17:18 UTC
Labels: question
